class Constants {
 var imagens = [
        'images/001-botanic.png',
        'images/002-botanic.png',
        'images/003-botanic.png',
        'images/004-botanic.png',
        'images/005-botanic.png',
        'images/006-botanic.png',
        'images/007-botanic.png',
        'images/008-botanic.png',
        'images/009-botanic.png',
        'images/010-botanic.png',
        'images/011-botanic.png',
        'images/012-botanic.png',
        'images/013-botanic.png',
        'images/014-botanic.png',
        'images/015-botanic.png',
        'images/016-botanic.png',
        'images/017-botanic.png',
        'images/018-botanic.png',
        'images/019-botanic.png',
        'images/020-botanic.png',
        'images/021-botanic.png',
        'images/022-botanic.png',
        'images/023-botanic.png',
        'images/024-botanic.png',
        'images/025-botanic.png',
        'images/026-botanic.png',
        'images/027-botanic.png',
        'images/028-botanic.png',
        'images/029-botanic.png',
        'images/030-botanic.png',
        'images/031-botanic.png',
        'images/032-botanic.png',
        'images/033-botanic.png',
        'images/034-botanic.png',
        'images/035-botanic.png',
        'images/036-botanic.png',
        'images/037-botanic.png',
        'images/038-botanic.png',
        'images/039-botanic.png',
        'images/040-botanic.png',
        'images/041-botanic.png',
        'images/042-botanic.png',
        'images/043-botanic.png',
        'images/044-botanic.png',
        'images/045-botanic.png',
        'images/046-botanic.png',
        'images/047-botanic.png',
        'images/048-botanic.png',
        'images/049-botanic.png',
        'images/050-botanic.png',
      ];

  var urlImage = 'http://192.168.1.14:8000/images';

  var url = 'http://192.168.1.14:8000/api';
}
