name: projeto_plantas
description: Plant Care.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  select_form_field: "^2.0.0"

  get:
  http: 
  provider: ^4.3.3
  shared_preferences: ^2.0.5

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets: 
    - images/
  
  fonts:
    - family: Gotham
      fonts:
        - asset: fonts/gotham.otf
    - family: Satisfy
      fonts:
        - asset: fonts/satisfy.ttf

  
